# Generated by Django 4.2.3 on 2023-07-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='hour_price',
            field=models.IntegerField(null=True),
        ),
    ]
